data=[
    {"name":"Yasmine Sabri","title":"Egyptian actress","country":"Egypt","followers":21.6},
    {"name":"Hannah El-Zahed","title":"Egyptian actress","country":"Egypt","followers":20.1},
    {"name":"Mohamed Hamaki","title":"Egyptian singer","country":"Egypt","followers":12.5},
    {"name":"Sherine Abdel-Wahab","title":"Egyptian award winning, singer, actress","country":"Egypt","followers":12.1},
    {"name":"Nelly Karim","title":"Multi-award-winning actress","country":"Egypt","followers":7.9},
    {"name":"Radwa El Sherbiny","title":" Lifestyle TV presenter","country":"Egypt","followers":15.4},
    {"name":"Ramez Galal","title":"Egyptian Actor","country":"Egypt","followers":12.7},
    {"name":"Ahmad Fahmy","title":"Egyptian Actor, Writer","country":"Egypt","followers":6.3},
    {"name":"Ahmed Hassan","title":"Egyptian Youtuber","country":"Egypt","followers":7},
    {"name":"Nesreen Tafesh","title":"Actress lightworker traveler","country":"Syria","followers":13},
    {"name":"Haifa Wehbe","title":"a Lebanese singer and actress","country":" Lebanon","followers":13.3},
    {"name":"Mohamed Salah","title":"Egyptian professional footballer","country":" Egypt","followers":63.2},
    {"name":"Mohamed Ramadan","title":"Egyptian Actor","country":" Egypt","followers":32.7},
    {"name":"Ahmed Abouhashima","title":"CEO of the Cairo-based Egyptian Steel","country":" Egypt","followers":30.1},
    {"name":"Yasmin Abdelaziz","title":"Egyptian actress","country":" Egypt","followers":19.3},
    {"name":"Nancy Ajram","title":"a Lebanese singer","country":"Lebanon","followers":39.5},
    {"name":"Tamer Hosny","title":"Egyptian singer","country":" Egypt","followers":39.8},
    {"name":"Ramy Sabry","title":"Egyptian singer","country":" Egypt","followers":13.1},
    {"name":"Donia Samir Ghanem","title":" Egyptian actress and singer","country":" Egypt","followers":15.3},
    {"name":"Asmaa Galal","title":"Egyptian actress","country":" Egypt","followers":4.4},
    ]
